# Generated by Django 4.2.4 on 2023-08-30 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account', models.IntegerField(default=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('availability', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Minigame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('result', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('gender', models.CharField(choices=[('Мужчина', 'Мужчина'), ('Женщина', 'Женщина'), (None, 'Не указан')], default=None, max_length=9)),
                ('own_money', models.IntegerField(default=1000)),
                ('credit', models.IntegerField(default=0)),
                ('bank', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMinigame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minigame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.minigame')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.equipment')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='equipment',
            field=models.ManyToManyField(through='data.PlayerEquipment', to='data.equipment'),
        ),
        migrations.AddField(
            model_name='player',
            name='minigame',
            field=models.ManyToManyField(through='data.PlayerMinigame', to='data.minigame'),
        ),
        migrations.AddField(
            model_name='player',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.shop'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.shop'),
        ),
    ]
